### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by glebfox** [Anastacia-Galaktionova/2-hw-data-1#2]
**ManufacturerBrowse**

Уведомление со статистикой не показывается.

**Car**

Нет валидации полей `registration number` и `production year` (см. задание)

**DataComBean**

Эффективнее было бы сразу загружать одно значение используя функцию `count()` в запросе

**Comment by Anastacia-Galaktionova** [comment]
Спасибо

Поправила валидацию полей registration number и production year.
Изменила запрос для загрузки значений, использовала count().
